# name: CI Pipeline

# on:
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]

# env:
#   FRONTEND_DIR: frontend
#   BACKEND_DIR: backend
#   IMAGE_NAME_FRONTEND: ${{ secrets.DOCKER_REGISTRY_USER }}/devops-masters-frontend
#   IMAGE_NAME_BACKEND: ${{ secrets.DOCKER_REGISTRY_USER }}/devops-masters-backend

# jobs:
#   build-frontend:
#     runs-on: ubuntu-latest
#     container: node:20
#     steps:
#       - uses: actions/checkout@v4
#       - name: Install dependencies and build frontend
#         run: |
#           cd $FRONTEND_DIR
#           npm ci
#           npm run build

#   build-backend:
#     runs-on: ubuntu-latest
#     container: mcr.microsoft.com/dotnet/sdk:8.0
#     steps:
#       - uses: actions/checkout@v4
#       - name: Restore and build backend
#         run: |
#           cd $BACKEND_DIR
#           dotnet restore
#           dotnet build --no-restore --configuration Release

#   test-frontend:
#     runs-on: ubuntu-latest
#     container: node:20
#     steps:
#       - uses: actions/checkout@v4
#       - name: Install dependencies and test frontend
#         run: |
#           cd $FRONTEND_DIR
#           npm ci
#           npm run test

#   test-backend:
#     runs-on: ubuntu-latest
#     container: mcr.microsoft.com/dotnet/sdk:8.0
#     steps:
#       - uses: actions/checkout@v4
#       - name: Test backend
#         run: |
#           cd $BACKEND_DIR
#           dotnet test

#   publish-frontend:
#     runs-on: ubuntu-latest
#     needs: [build-frontend]
#     steps:
#       - uses: actions/checkout@v4
#       - name: Set up Docker
#         uses: docker/setup-buildx-action@v3
#       - name: Login to DockerHub
#         uses: docker/login-action@v3
#         with:
#           username: ${{ secrets.DOCKER_REGISTRY_USER }}
#           password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
#       - name: Build and push frontend image
#         run: |
#           docker build -t $IMAGE_NAME_FRONTEND:${{ github.sha }} -t $IMAGE_NAME_FRONTEND:latest $FRONTEND_DIR
#           docker push $IMAGE_NAME_FRONTEND:${{ github.sha }}
#           docker push $IMAGE_NAME_FRONTEND:latest

#   publish-backend:
#     runs-on: ubuntu-latest
#     needs: [build-backend]
#     steps:
#       - uses: actions/checkout@v4
#       - name: Set up Docker
#         uses: docker/setup-buildx-action@v3
#       - name: Login to DockerHub
#         uses: docker/login-action@v3
#         with:
#           username: ${{ secrets.DOCKER_REGISTRY_USER }}
#           password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
#       - name: Build and push backend image
#         run: |
#           docker build -t $IMAGE_NAME_BACKEND:${{ github.sha }} -t $IMAGE_NAME_BACKEND:latest $BACKEND_DIR
#           docker push $IMAGE_NAME_BACKEND:${{ github.sha }}
#           docker push $IMAGE_NAME_BACKEND:latest
